namespace MultiTool.Utils.Markdown;

public enum MarkdownTokenType {
    H1, H2, H3, H4, H5, H6,
    BOLD, ITALIC, STRIKETHROUGH, HIGHLIGHT, SUBSCRIPT, SUPERSCRIPT,
    BLOCKQUOTE, HORIZONTAL_RULE, CODE_IN_LINE, MULTILINE_CODE,
    ORDERED_LIST_ITEM, UNORDERED_LIST_ITEM, TASK_LIST_ITEM_CHECKED, TASK_LIST_ITEM_UNCHECKED,
    LINK, IMAGE, TABLE_ROW, FOOT_NOTE_REFERENCE, FOOT_NOTE_DEFINITION,
    DEFINITIONT_ERM, DEFINITION_DESCRIPTION, EMOJI, TEXT, NEW_LINE
}